name: Rust CleverCloud Deploy
on: [push, workflow_dispatch]
jobs:

  deploy:
    name: CleverCloud deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Job triggered by ${{ github.event_name }} event."
      - run: echo "🐧 Job running on ${{ runner.os }}."
      - run: echo "  Repository ${{ github.repository }}. Branch ${{ github.ref }}."
      - run: |
          ls ${{ github.workspace }}
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: Tarnyko/actions-clever-cloud@v1-force
        with:
          timeout: 300
          appID: app_9e6ed579-9e56-42c5-81e6-3bf8ac5ee049
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
